[package]
name = "onsen"
version = "0.6.2"
edition = "2021"
authors = ["Christian Thäter <ct@pipapo.org>"]
description = "Memory pool"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cehteh/onsen.git"
keywords = ["allocator", "pool"]

[features]
default = ["bitmap_scan"]
# scanning the bitmap on pool drop makes pool dropping slower but we do not need to update a
# counter on each allocation/free. Improving performance in the normal case.
bitmap_scan = []

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"]}

[[bench]]
name = "baseline"
harness = false

[[bench]]
name = "simulated_work"
harness = false

[badges]
maintenance = { status = "actively-developed" }

