[package]
name = "onsen"
version = "0.6.1"
edition = "2021"
authors = ["Christian Thäter <ct@pipapo.org>"]
description = "Memory pool"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cehteh/onsen.git"
keywords = ["allocator", "pool"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "baseline"
harness = false

[badges]
maintenance = { status = "actively-developed" }

